# Generated by Django 4.2.1 on 2023-05-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_remove_comment_post_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
    ]
