# Generated by Django 4.2.1 on 2023-05-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_remove_comment_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150, verbose_name='post title')),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='uploads/post_img', verbose_name='Post Image')),
                ('Profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.profile')),
                ('tags', models.ManyToManyField(to='first_app.tags', verbose_name='post tags')),
            ],
        ),
    ]
