# Generated by Django 4.2.1 on 2023-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_remove_comment_post_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profle_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
