# Generated by Django 4.2.1 on 2023-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_alter_profile_profle_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profle_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to=''),
        ),
    ]
