# Generated by Django 4.2.1 on 2023-05-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhor',
            new_name='author',
        ),
    ]
