# Generated by Django 4.2.1 on 2023-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='alaye.jpg', null=True, upload_to='static/img', verbose_name='Post Image'),
        ),
    ]
